# Generated by Django 4.2.1 on 2023-05-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_reply_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply_comment',
            old_name='comment',
            new_name='replay_comment',
        ),
        migrations.AddField(
            model_name='reply_comment',
            name='for_comment',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='main.comment'),
            preserve_default=False,
        ),
    ]
