# Generated by Django 4.2.1 on 2023-05-31 12:21

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_comment_reply_comment_replay_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
    ]
