# Generated by Django 4.2.1 on 2023-06-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
