# Generated by Django 4.2.1 on 2023-06-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_article_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
