# Generated by Django 4.2.1 on 2023-06-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_article_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
